"""
Ingest synthetic e-commerce CSV datasets into a SQLite database.

This script expects the CSV files generated by `generate_ecom_data.py` inside
the `data/` directory and loads them into tables within `db/ecom.db`.
"""

from __future__ import annotations

import sqlite3
from pathlib import Path
from typing import Dict, Iterable, List, Tuple

import pandas as pd


PROJECT_ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = PROJECT_ROOT / "data"
DB_DIR = PROJECT_ROOT / "db"
DB_PATH = DB_DIR / "ecom.db"


TABLE_SCHEMAS: Dict[str, str] = {
    "customers": """
        CREATE TABLE IF NOT EXISTS customers (
            customer_id INTEGER PRIMARY KEY,
            name TEXT NOT NULL,
            email TEXT NOT NULL UNIQUE,
            signup_date TEXT NOT NULL,
            location TEXT NOT NULL
        );
    """,
    "products": """
        CREATE TABLE IF NOT EXISTS products (
            product_id INTEGER PRIMARY KEY,
            name TEXT NOT NULL,
            category TEXT NOT NULL,
            price REAL NOT NULL
        );
    """,
    "orders": """
        CREATE TABLE IF NOT EXISTS orders (
            order_id INTEGER PRIMARY KEY,
            customer_id INTEGER NOT NULL,
            order_date TEXT NOT NULL,
            total_amount REAL NOT NULL,
            FOREIGN KEY (customer_id) REFERENCES customers(customer_id)
        );
    """,
    "order_items": """
        CREATE TABLE IF NOT EXISTS order_items (
            order_item_id INTEGER PRIMARY KEY,
            order_id INTEGER NOT NULL,
            product_id INTEGER NOT NULL,
            quantity INTEGER NOT NULL,
            item_price REAL NOT NULL,
            FOREIGN KEY (order_id) REFERENCES orders(order_id),
            FOREIGN KEY (product_id) REFERENCES products(product_id)
        );
    """,
    "payments": """
        CREATE TABLE IF NOT EXISTS payments (
            payment_id INTEGER PRIMARY KEY,
            order_id INTEGER NOT NULL,
            payment_method TEXT NOT NULL,
            status TEXT NOT NULL,
            payment_date TEXT NOT NULL,
            FOREIGN KEY (order_id) REFERENCES orders(order_id)
        );
    """,
}


CSV_FILES: Dict[str, str] = {
    "customers": "customers.csv",
    "products": "products.csv",
    "orders": "orders.csv",
    "order_items": "order_items.csv",
    "payments": "payments.csv",
}


def ensure_directories() -> None:
    DB_DIR.mkdir(parents=True, exist_ok=True)
    if not DATA_DIR.exists():
        raise FileNotFoundError(
            f"Data directory not found at {DATA_DIR}. Run generate_ecom_data.py first."
        )


def load_dataframe(name: str) -> pd.DataFrame:
    csv_path = DATA_DIR / CSV_FILES[name]
    if not csv_path.exists():
        raise FileNotFoundError(f"CSV file for {name} not found: {csv_path}")
    df = pd.read_csv(csv_path)
    return df


def create_tables(conn: sqlite3.Connection) -> None:
    for ddl in TABLE_SCHEMAS.values():
        conn.execute(ddl)
    conn.commit()


def dataframe_rows(df: pd.DataFrame) -> Iterable[Tuple]:
    """Yield tuples suitable for insertion, replacing NaN with None."""
    clean_df = df.where(pd.notnull(df), None)
    return (tuple(row) for row in clean_df.itertuples(index=False, name=None))


def insert_dataframe(
    conn: sqlite3.Connection, table: str, df: pd.DataFrame
) -> int:
    columns = list(df.columns)
    placeholders = ", ".join(["?"] * len(columns))
    column_clause = ", ".join(columns)
    sql = f"INSERT OR REPLACE INTO {table} ({column_clause}) VALUES ({placeholders})"
    rows = list(dataframe_rows(df))
    conn.executemany(sql, rows)
    conn.commit()
    return len(rows)


def ingest() -> None:
    ensure_directories()
    with sqlite3.connect(DB_PATH) as conn:
        conn.execute("PRAGMA foreign_keys = ON;")
        create_tables(conn)

        insertion_order: List[str] = [
            "customers",
            "products",
            "orders",
            "order_items",
            "payments",
        ]

        for table in insertion_order:
            df = load_dataframe(table)
            inserted = insert_dataframe(conn, table, df)
            print(f"Inserted {inserted} rows into {table}")

    print(f"SQLite database created at {DB_PATH}")


if __name__ == "__main__":
    ingest()

